halfcheetah-medium-v2:
  eta: 0.2
  lmbda: 0.1
halfcheetah-medium-replay-v2:
  eta: 0.2
  lmbda: 1.0
halfcheetah-medium-expert-v2:
  eta: 25.0
  lmbda: 1.0
hopper-medium-v2:
  eta: 1.0
  lmbda: 0.5
hopper-medium-replay-v2:
  eta: 0.2
  lmbda: 1.0
hopper-medium-expert-v2:
  eta: 50.0
  lmbda: 1.0
walker2d-medium-v2:
  eta: 1.0
  lmbda: 0.1
walker2d-medium-replay-v2:
  eta: 0.68
  lmbda: 1.0
walker2d-medium-expert-v2:
  eta: 20.0
  lmbda: 1.0